
<template>
    <div class="modal">
        <span> 
            I started this as a fun project to learn VueJS, and I had a good time
            making this. In fact, I had no idea what I was doing when the project started, 
            and this come out as a result. Pretty funny. All the images are generated by LeonardoAI, mostly by DreamShaper v5/6.
            All the text are generated by ChatGPT 3.5. The hover effect ideas are from 
            tympanus.net. I do not want to consider this little project finished, and I'm looking forward to make more improvements.
        </span>
        <span> - Henry Oo </span>
    </div>
</template>

<script>
    export default{

    }
</script>

<style scoped>
    .modal{
        position: fixed;
        top: 50%; left: 50%;
        transform: translate(-50%,-50%);
        width: 40%;
        height: 40%;
        display: grid;
        place-items: center;
        z-index: 3;
        font-size: medium;
        background-color: rgba(0,0,0,1);
        border-color: whitesmoke;
        border-style: solid;
        border-width: 1px;
        border-radius: 4px;
        padding: 20px;
    }
</style>